# Generated by Django 4.1 on 2025-12-08 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='completada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'stock'], name='pos_product_activo_08baf0_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo', 'activo'], name='pos_product_codigo_79487e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha', 'completada'], name='pos_venta_fecha_dc1202_idx'),
        ),
    ]
