# Generated by Django 4.1 on 2025-12-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras', 'activo'], name='pos_product_codigo__28f9a9_idx'),
        ),
    ]
