# Generated by Django 4.1 on 2025-12-10 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0004_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Caja')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CajaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Inicial')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final')),
            ],
            options={
                'verbose_name': 'Caja Usuario',
                'verbose_name_plural': 'Cajas Usuarios',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Recibido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cajausuario',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.caja', verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='cajausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pos.caja', verbose_name='Caja'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['caja', 'fecha'], name='pos_venta_caja_id_708460_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'fecha'], name='pos_venta_usuario_e23ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='cajausuario',
            index=models.Index(fields=['caja', 'fecha_cierre'], name='pos_cajausu_caja_id_96cec5_idx'),
        ),
        migrations.AddIndex(
            model_name='cajausuario',
            index=models.Index(fields=['usuario', 'fecha_cierre'], name='pos_cajausu_usuario_aa738e_idx'),
        ),
    ]
