# Generated by Django 4.1 on 2025-12-10 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0006_venta_anulada_venta_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='editada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Editada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_ultima_edicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Última Edición'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_ultima_edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Editó'),
        ),
    ]
