# Generated by Django 4.1 on 2025-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_venta_editada_venta_fecha_ultima_edicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_devolucion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto devuelto al cliente cuando se editó la venta', max_digits=10, null=True, verbose_name='Monto Devolución'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto adicional pagado por el cliente cuando se editó la venta', max_digits=10, null=True, verbose_name='Monto Pago Adicional'),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_edicion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Edición'),
        ),
    ]
