# Generated by Django 4.1 on 2025-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_venta_monto_devolucion_venta_monto_pago_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='email_cliente',
            field=models.EmailField(blank=True, help_text='Email del cliente para envío de recibo', max_length=254, null=True, verbose_name='Email del Cliente'),
        ),
    ]
