# Generated by Django 4.1 on 2025-12-10 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0009_venta_email_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], default='ingreso', max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock Anterior')),
                ('stock_nuevo', models.IntegerField(verbose_name='Stock Nuevo')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['-fecha', 'producto'], name='pos_movimie_fecha_3c2b21_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', 'tipo'], name='pos_movimie_product_58db3c_idx'),
        ),
    ]
