# Generated by Django 4.1 on 2025-12-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0010_movimientostock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='PIN de 4 dígitos para acceso rápido', max_length=4, verbose_name='PIN')),
                ('pin_establecido', models.BooleanField(default=False, verbose_name='PIN Establecido')),
                ('fecha_creacion_pin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación del PIN')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
