# Generated by Django 4.1 on 2025-12-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0011_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.TextField(help_text='Descripción del gasto', verbose_name='Descripción')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('caja_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='pos.cajausuario', verbose_name='Caja Usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Gasto de Caja',
                'verbose_name_plural': 'Gastos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['-fecha', 'caja_usuario'], name='pos_gastoca_fecha_008ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['caja_usuario', 'fecha'], name='pos_gastoca_caja_us_08aeef_idx'),
        ),
    ]
