# Generated by Django 4.1 on 2025-12-10 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0012_gastocaja_gastocaja_pos_gastoca_fecha_008ccf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Caja de Gastos', max_length=100, verbose_name='Nombre de la Caja')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Caja de Gastos',
                'verbose_name_plural': 'Cajas de Gastos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CajaGastosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Inicial')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final')),
            ],
            options={
                'verbose_name': 'Caja Gastos Usuario',
                'verbose_name_plural': 'Cajas Gastos Usuarios',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AlterModelOptions(
            name='gastocaja',
            options={'ordering': ['-fecha'], 'verbose_name': 'Gasto/Ingreso de Caja', 'verbose_name_plural': 'Gastos/Ingresos de Caja'},
        ),
        migrations.RemoveIndex(
            model_name='gastocaja',
            name='pos_gastoca_fecha_008ccf_idx',
        ),
        migrations.RemoveIndex(
            model_name='gastocaja',
            name='pos_gastoca_caja_us_08aeef_idx',
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso')], default='gasto', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='gastocaja',
            name='caja_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_antiguos', to='pos.cajausuario', verbose_name='Caja Usuario (Antigua)'),
        ),
        migrations.AlterField(
            model_name='gastocaja',
            name='descripcion',
            field=models.TextField(help_text='Descripción del gasto o ingreso', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='cajagastosusuario',
            name='caja_gastos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='pos.cajagastos', verbose_name='Caja de Gastos'),
        ),
        migrations.AddField(
            model_name='cajagastosusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='caja_gastos_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='pos.cajagastosusuario', verbose_name='Caja Gastos Usuario'),
        ),
        migrations.AddIndex(
            model_name='cajagastosusuario',
            index=models.Index(fields=['usuario', 'fecha_cierre'], name='pos_cajagas_usuario_1c3d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cajagastosusuario',
            index=models.Index(fields=['caja_gastos', 'fecha_cierre'], name='pos_cajagas_caja_ga_43c438_idx'),
        ),
    ]
