# Generated by Django 4.1 on 2025-12-10 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0013_cajagastos_cajagastosusuario_alter_gastocaja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor asociado a la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
