# Generated by Django 4.1 on 2025-12-10 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0014_venta_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePotencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_interes', models.CharField(choices=[('mayorista', 'Venta Mayorista'), ('web', 'Venta Web'), ('ambos', 'Ambos')], default='mayorista', max_length=20, verbose_name='Tipo de Interés')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje o Comentarios')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_proceso', 'En Proceso'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], db_index=True, default='nuevo', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('fecha_contacto', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Contacto')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas privadas para el equipo', null=True, verbose_name='Notas Internas')),
                ('usuario_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_contactados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Contactó')),
            ],
            options={
                'verbose_name': 'Cliente Potencial',
                'verbose_name_plural': 'Clientes Potenciales',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='clientepotencial',
            index=models.Index(fields=['-fecha_registro', 'estado'], name='pos_cliente_fecha_r_e4d9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='clientepotencial',
            index=models.Index(fields=['tipo_interes', 'estado'], name='pos_cliente_tipo_in_a0edcd_idx'),
        ),
        migrations.AddIndex(
            model_name='clientepotencial',
            index=models.Index(fields=['email'], name='pos_cliente_email_121626_idx'),
        ),
    ]
