# Generated by Django 4.1 on 2025-12-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0015_clientepotencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Factura')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_mercancia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ingreso de Mercancía',
                'verbose_name_plural': 'Ingresos de Mercancía',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalidaMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('devolucion', 'Devolución'), ('merma', 'Merma'), ('traslado', 'Traslado'), ('donacion', 'Donación'), ('otro', 'Otro')], default='merma', max_length=20, verbose_name='Tipo de Salida')),
                ('destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mercancia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Salida de Mercancía',
                'verbose_name_plural': 'Salidas de Mercancía',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemSalidaMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.producto', verbose_name='Producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salidamercancia', verbose_name='Salida')),
            ],
            options={
                'verbose_name': 'Item de Salida',
                'verbose_name_plural': 'Items de Salida',
            },
        ),
        migrations.CreateModel(
            name='ItemIngresoMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.ingresomercancia', verbose_name='Ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Ingreso',
                'verbose_name_plural': 'Items de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='CampanaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('redes_sociales', 'Redes Sociales'), ('promocion', 'Promoción'), ('descuento', 'Descuento')], max_length=20, verbose_name='Tipo de Campaña')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='planificada', max_length=20, verbose_name='Estado')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto')),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Descuento')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('productos', models.ManyToManyField(blank=True, to='pos.producto', verbose_name='Productos Relacionados')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Campaña de Marketing',
                'verbose_name_plural': 'Campañas de Marketing',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
