# Generated by Django 4.1 on 2025-12-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_ingresomercancia_salidamercancia_itemsalidamercancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajagastosusuario',
            name='monto_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto Final'),
        ),
        migrations.AlterField(
            model_name='cajagastosusuario',
            name='monto_inicial',
            field=models.IntegerField(default=0, verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='cajausuario',
            name='monto_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto Final'),
        ),
        migrations.AlterField(
            model_name='cajausuario',
            name='monto_inicial',
            field=models.IntegerField(default=0, verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='campanamarketing',
            name='presupuesto',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='gastocaja',
            name='monto',
            field=models.IntegerField(default=0, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='ingresomercancia',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itemingresomercancia',
            name='precio_compra',
            field=models.IntegerField(default=0, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='itemingresomercancia',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.IntegerField(default=0, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_devolucion',
            field=models.IntegerField(blank=True, default=0, help_text='Monto devuelto al cliente cuando se editó la venta', null=True, verbose_name='Monto Devolución'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_pago_adicional',
            field=models.IntegerField(blank=True, default=0, help_text='Monto adicional pagado por el cliente cuando se editó la venta', null=True, verbose_name='Monto Pago Adicional'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_recibido',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto Recibido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
