# Generated by Django 4.1 on 2025-12-10 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0017_cambiar_precios_a_enteros'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistradoraActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registradora_id', models.IntegerField(help_text='ID de la registradora (1, 2 o 3)', unique=True, verbose_name='ID de Registradora')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registradoras_activas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registradora Activa',
                'verbose_name_plural': 'Registradoras Activas',
                'ordering': ['registradora_id'],
            },
        ),
    ]
