# Generated by Django 4.1 on 2025-12-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_registradoraactiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='registradora_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID de la registradora (1, 2 o 3) desde donde se realizó la venta', null=True, verbose_name='Registradora'),
        ),
    ]
