# Generated by Django 4.1 on 2025-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_venta_registradora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='atributo',
            field=models.CharField(blank=True, help_text='Atributo adicional del producto (ej: color, tamaño, modelo, etc.)', max_length=200, null=True, verbose_name='Atributo'),
        ),
    ]
