# Generated by Django 4.1 on 2025-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_producto_atributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingresomercancia',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
