# Generated by Django 4.1 on 2025-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_itemingresomercancia_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingresomercancia',
            name='procesado',
            field=models.BooleanField(default=False, verbose_name='Procesado'),
        ),
    ]
