# Generated by Django 4.1 on 2025-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_itemingresomercancia_procesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('codigo', 'atributo'), name='unique_codigo_atributo'),
        ),
    ]
