# Generated by Django 4.1 on 2025-12-17 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0023_cambiar_unique_codigo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código del producto', max_length=50, verbose_name='Código')),
                ('atributo', models.CharField(blank=True, help_text='Atributo del producto', max_length=200, null=True, verbose_name='Atributo')),
                ('cantidad_contada', models.IntegerField(help_text='Cantidad física contada', verbose_name='Cantidad Contada')),
                ('fecha_conteo', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Conteo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-fecha_conteo'],
            },
        ),
        migrations.AddIndex(
            model_name='conteofisico',
            index=models.Index(fields=['codigo', 'atributo', '-fecha_conteo'], name='pos_conteof_codigo_ea93fb_idx'),
        ),
        migrations.AddIndex(
            model_name='conteofisico',
            index=models.Index(fields=['-fecha_conteo'], name='pos_conteof_fecha_c_2f35e7_idx'),
        ),
    ]
